version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file
      - mvn clean package -DskipTests

    post_build:
      commands:
        - echo Build complete

artifacts:
  files:
    - target/springboot-crud-app.jar

  discard-paths: yes