spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  properties:
    hibernate:
      use-new-id-generator-mappings: false
      #dialect: org.hibernate.dialect.MySQL5Dialect
    max_allowed_packet: 200

server:
  port: 9000